model:
  network: "ResNet50"
  in_channels: 3
  num_classes: 10

dataloader:
  dataset_path: "/home/lorrentz/DATA/cifar-10/"
  batch_size: 8
  shuffle: False
  num_workers: 4
  pin_memory: False
  drop_last: True
  persistent_workers: False

training:
  epochs: 75
  validate_period: 5
  device: 0
  log_path: "./log"
  deterministic: True
  optimizer:
    type: "SGD"
    lr: 0.001
    momentum: 0.9