model:
  network: "ResNet50"
  in_channels: 3
  num_classes: 10

dataloader:
  dataset_path: "/home/lorrentz/DATA/cifar-10/"
  batch_size: 16
  shuffle: False
  num_workers: 4
  pin_memory: False
  drop_last: True
  persistent_workers: False

training:
  epochs: 100
  validate_period: 5
  device: 0
  log_path: "./log"
  deterministic: True
  optimizer:
    type: "SGD"
    lr: 0.004
    momentum: 0.9
    weight_decay: 0.0001
  scheduler:
    type: "StepLR"
    step_size: 80
    gamma: 0.25